---

- hosts: localhost
  gather_facts: no
  tasks:
    
    - name: "Check Parameters"
      fail:
        msg: "SS_Name (Stack Set name) paramater  must be specified."
      when: (not SS_Name)

    - name: Include Full-PAS Variables
      include_vars:
        file: vars/AOB-MR-StackSet-Params.yml
        name: ss_params

###########################ss_deploy#########################
    - name: "Deploy Cloud Formation Stack Set"
      cloudformation_stack_set:
        name: "{{ SS_Name }}"
      vars:
        cf_template_parameters: "{{ ss_params.template_parameters }}"
