---

- hosts: localhost
  gather_facts: no
  tasks:

    - name: Include AOB Variables
      include_vars:
        file: vars/AOB-Params.yml
        name: aob_vars
    
    - name: Stack Name
      set_fact:
        CFStackName: "AOB-CF"
        SSStackName: "AOB-SS"

    - name: Deploy AOB from CloudFormation Template
      include_role:
        name: cf_deploy
      vars:
        cf_template_file: "{{ aob_vars.CloudFormation_parameters.TemplatePath }}"
        cf_template_parameters: "{{ aob_vars.CloudFormation_parameters }}"
    
    - name: Deploy 
      include_role:
        name: ss_deploy
      vars:
        cf_template_file: "{{ aob_vars.StackSet_parameters.TemplatePath }}"
        cf_template_parameters: "{{ aob_vars.StackSet_parameters }}"
    