---

- hosts: localhost
  gather_facts: no
  tasks:

    - name: Include AOB Variables
      include_vars:
        file: vars/AOB-Params.yml
        name: aob_vars
    
    - name: Stack Name
      set_fact:
        CFStackName: "AOB-CF"
        SSStackName: "AOB-SS"

    - name: Deploy AOB CloudFormation
      include_role:
        name: cf_deploy
      vars:
        cf_template_file: "{{ aob_vars.CFTemplatePath }}"
        cf_template_parameters: "{{ aob_vars.CloudFormation_parameters }}"
        runtime_parameters: "{{ aob_vars.Runtime_parameters }}"
    
    - name: Deploy AOB StackSet
      include_role:
        name: ss_deploy
      vars:
        ss_template_file: "{{ aob_vars.SSTemplatePath }}"
        ss_template_parameters: "{{ cf_arn }}"
        runtime_parameters: "{{ aob_vars.Runtime_parameters }}"
    